stages:
  data_ingestion:
    cmd: python src/AIDrugDiscovery/pipeline/stage_01_data_ingestion.py
    deps:
      - src/AIDrugDiscovery/pipeline/stage_01_data_ingestion.py
      - src/AIDrugDiscovery/components/data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/